name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: haskell-actions/setup@v2

      - name: Haskell
        run: |
          cabal install --lib split
          cabal install --lib containers
          runhaskell haskell.hs

      - name: Optiscope
        run: |
          ./optiscope.py

      - name: Tromp
        run: |
          ./tromp.py
